piVersion: apps/v1
kind: Deployment
metadata:
  name: kbt1-ollilove-transfer-service
  labels:
    app: kbt1-ollilove-transfer-service
spec:
  selector:
    matchLabels:
      app: kbt1-ollilove-transfer-service
  replicas: 1
  template:
    metadata:
      name: kbt1-ollilove-transfer-service
      labels:
        app: kbt1-ollilove-transfer-service
    spec:
      containers:
        - name: kbt1-ollilove-transfer-service
          image: docker.io/gyuminn/kbt1-ollilove-transfer-service:1.0.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: kbt1-ollilove-transfer-service-cm
            - secretRef:
                name: kbt1-ollilove-transfer-service-secret
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: media-data
              mountPath: /root/data
              readOnly: false
      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: kbt1-ollilove-transfer-pvc
            readOnly: false

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kbt1-ollilove-user-service-cm
data:
  DB_SERVER: kbt1-ollilove-mysql
  DB_PORT: "3306"
  DB_NAME: "kbt1"

---

kind: Secret
apiVersion: v1
metadata:
  name: kbt1-ollilove-user-service-secret
type: Opaque
data:
  DB_USERNAME: ZmFrZXIK            #echo {username} | base64
  DB_PASSWORD: a2J0MUJlc3QhCg==    #echo {password} | base64

---

apiVersion: v1
kind: Service
metadata:
  name: kbt1-ollilove-user-service
spec:
  type: ClusterIP
  selector:
    app: kbt1-ollilove-user-service
  ports:
    - name: kbt1-ollilove-user-service
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kbt1-ollilove-user-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: kbt1-ollilove-user-api.165.192.105.60.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: kbt1-ollilove-user-service
                port:
                  number: 8080